### ISSUE TITLE
Update plotting tests

### ISSUE THREAD

**Issue by samjrholt** [ubermag/discretisedfield#413]
Sam:
- [x] test_mpl_scalar #460 
- [x] test_mpl_lightess
- [x] test_mpl_vector
- [x] test_mpl_contour
- [x] test_mpl #461 

Martin:
- [x] test_hv_scalar #490
- [x] test_hv_vector #490
- [x] test_hv_contour #490
- [x] test_hv #490

Needed?:
- [x] test_k3d
- [x] test_k3d_nonzero
- [x] test_k3d_vector
- [x] test_plot_large_sample

**Comment by lang-m** [comment]
We should probably add some basic tests for `k3d` to ensure that it fails with reasonable errors if `ndims`/`nvdims` are not correct.

**Comment by lang-m** [comment]
`k3d` (in Ubermag) only supports 3d fields. Tests are already implemented.
