### ISSUE TITLE
Update file tests

### ISSUE THREAD

**Issue by samjrholt** [ubermag/discretisedfield#414]
- [x] test_write_read_ovf (#484)
- [x] test_write_read_vtk (#484)
- [x] test_write_read_hdf5 (#377)
- [x] test_write_read_invalid_extension (#484)
