### ISSUE TITLE
discretisedfield 1.0 todo-list and discussion

### ISSUE THREAD

**Issue by marijanbeg** [ubermag/discretisedfield#76]
The purpose of this issue is to collect and discuss todo-items on what could/should be done for `discretisedfield` 1.0 future release.

- [ ] Line object operations - similar to `Field` (add, subtract, etc...)
- [x] #312
- [x] Extend tests and document functionality (notebooks) for features in 2020 release
- [x] Do HSV plots work with `np.nan` values (`lightness_field` and `filter_field`)
- [ ] Find a way of recognising contributions - promote tools
- [x] Review docs
- [x] JupyterLab 3.0 widget issues
- [ ] ~`k3d`~ `pyvista` line plotting
- [x] Modernise Python syntax where possible
- [x] Colorbar for HLS plots
- [x] mesh alignment to `__contains__` operator
- [x] make integral method private

**Comment by lang-m** [comment]
- [ ] Additional plotting functionality based on HoloViews for better interactive plots

**Comment by samjrholt** [comment]
- [ ] Different dimensional meshes e.g. truly 2D meshes

**Comment by fangohr** [comment]
- [ ] add test(s) for `demag_tensor(mesh)` (see https://app.codecov.io/gh/ubermag/discretisedfield/blob/master/discretisedfield/tools/tools.py)
